name: Azure Static Web Apps CI/CD

on:
  gollum

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: checkout wiki
        uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}.wiki
          path: 'wiki'
      - name: install mkdocs
        run:  |
          pip install mkdocs
      - name: check wiki repo content
        run: |
          ls ./wiki -al
      
#      - name: Build And Deploy
#        id: builddeploy
#        uses: Azure/static-web-apps-deploy@v1
#        with:
#          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
#          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
#          action: "upload"
#          ###### Repository/Build Configurations ######
#          app_location: "src" # App source code path relative to repository root
#          api_location: "api" # Api source code path relative to repository root - optional
#          output_location: "public" # Built app content directory, relative to app_location - optional
#          ###### End of Repository/Build Configurations ######
