name: Azure Static Web Apps CI/CD

on:
  gollum

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: checkout wiki
        uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}.wiki
          path: 'docs'
      - name: install mkdocs and plugins
        run:  |
          pip install mkdocs mkdocs-exclude
      - name: write mkdocs config
        env:
          CONFIG_FILE: mkdocs.yml
          SITE_NAME: ${{github.repository}} wiki
          REPO_URL: https://github.com/${{github.repository}}/wiki
        run: |
          touch "$CONFIG_FILE"
          echo "site_name: $SITE_NAME"   >> "$CONFIG_FILE"
          echo "repo_url: $REPO_URL"     >> "$CONFIG_FILE"
          echo "edit_uri: ''"            >> "$CONFIG_FILE"

          # setup theme
          echo "theme:"                  >> "$CONFIG_FILE"
          echo "  name: readthedocs"     >> "$CONFIG_FILE"

          # setup plugins
          echo "plugins:"                >> "$CONFIG_FILE"
          echo "  - exclude:"            >> "$CONFIG_FILE"
          echo "      glob: "            >> "$CONFIG_FILE"
          echo '        - "_Footer.md"'  >> "$CONFIG_FILE"
          echo '        - "_Sidebar.md"' >> "$CONFIG_FILE"
      - name: add page title to content
        run: |
          for file in $(find ./docs/ -name '*.md')
          do
            filename=$(basename -- "$file")
            title=$(echo "${filename%.*}" | tr '-' ' ')
            echo "filename $filename -> $title"   

            echo -e "Title: $title\n\n$(cat $file)" > "$file"
          done
      - name: rename home to index
        run:  |
          if [[ ! -f ./docs/index.md ]]; then 
            find ./docs/ -maxdepth 1 -iname home.md -exec mv {} ./docs/index.md \;
          fi
      - name: build site
        run: makedocs build
        
        
      
#      - name: Build And Deploy
#        id: builddeploy
#        uses: Azure/static-web-apps-deploy@v1
#        with:
#          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
#          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
#          action: "upload"
#          ###### Repository/Build Configurations ######
#          app_location: "src" # App source code path relative to repository root
#          api_location: "api" # Api source code path relative to repository root - optional
#          output_location: "public" # Built app content directory, relative to app_location - optional
#          ###### End of Repository/Build Configurations ######
